#!/usr/bin/env python3
"""Run the first descriptive pilot analysis on Reddit COVID vaccine data.

This script does not validate the correction label. It uses the
`candidate_correction` flag generated by `prepare_covidvaccine_dataset.py` as a
retrieval aid for feasibility analysis and annotation sampling.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import random
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable


COMMUNITY_GROUPS = {
    "skeptical_or_anti_institutional": {
        "antivaxxers",
        "conservative",
        "conspiracy",
        "conspiracy_commons",
        "conspiracytheories",
        "nonewnormal",
        "trueantivaccination",
    },
    "public_health_or_news": {
        "coronavirus",
        "covid19",
        "news",
    },
    "vaccine_experience_or_health": {
        "covidvaccinated",
        "covidvaccine",
        "vaccines",
    },
}

REMOVED_AUTHORS = {"", "[deleted]", "deleted", "automoderator"}


def iter_jsonl(path: Path) -> Iterable[dict[str, Any]]:
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                yield json.loads(line)


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")


def write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def community_group(subreddit: str | None) -> str:
    subreddit = normalize_token(subreddit)
    for group, subreddits in COMMUNITY_GROUPS.items():
        if subreddit in subreddits:
            return group
    return "other"


def normalize_token(value: Any) -> str:
    return str(value or "").strip().lower()


def normalize_author(value: Any) -> str | None:
    author = normalize_token(value)
    if author in REMOVED_AUTHORS:
        return None
    return author


def entropy(counts: Counter[str]) -> float:
    total = sum(counts.values())
    if total <= 0:
        return 0.0
    out = 0.0
    for count in counts.values():
        p = count / total
        if p > 0:
            out -= p * math.log(p)
    return out


def load_comments(path: Path) -> list[dict[str, Any]]:
    comments = []
    for row in iter_jsonl(path):
        subreddit = normalize_token(row.get("subreddit"))
        author = normalize_author(row.get("author"))
        row["subreddit"] = subreddit
        row["author_clean"] = author
        row["community_group_proxy"] = community_group(subreddit)
        row["candidate_correction"] = bool(row.get("candidate_correction"))
        comments.append(row)
    return comments


def build_thread_profiles(comments: list[dict[str, Any]]) -> list[dict[str, Any]]:
    stats: dict[str, dict[str, Any]] = {}
    authors_by_thread: dict[str, set[str]] = defaultdict(set)
    candidate_authors_by_thread: dict[str, set[str]] = defaultdict(set)

    for comment in comments:
        submission_id = str(comment.get("submission_id") or "")
        if not submission_id:
            continue
        if submission_id not in stats:
            stats[submission_id] = {
                "submission_id": submission_id,
                "subreddit": comment.get("subreddit"),
                "community_group_proxy": comment.get("community_group_proxy"),
                "submission_title": comment.get("submission_title"),
                "comments": 0,
                "candidate_corrections": 0,
            }
        stats[submission_id]["comments"] += 1
        author = comment.get("author_clean")
        if author:
            authors_by_thread[submission_id].add(author)
            if comment["candidate_correction"]:
                candidate_authors_by_thread[submission_id].add(author)
        if comment["candidate_correction"]:
            stats[submission_id]["candidate_corrections"] += 1

    rows = []
    for submission_id, row in stats.items():
        unique_authors = len(authors_by_thread[submission_id])
        candidate_authors = len(candidate_authors_by_thread[submission_id])
        row["unique_authors"] = unique_authors
        row["candidate_correctors"] = candidate_authors
        row["exposed_but_not_candidate_correctors"] = max(unique_authors - candidate_authors, 0)
        row["has_candidate_correction"] = row["candidate_corrections"] > 0
        row["candidate_comment_rate"] = safe_div(row["candidate_corrections"], row["comments"])
        row["candidate_author_rate"] = safe_div(candidate_authors, unique_authors)
        rows.append(row)

    return sorted(rows, key=lambda item: (item["candidate_corrections"], item["comments"]), reverse=True)


def build_user_profiles(comments: list[dict[str, Any]]) -> list[dict[str, Any]]:
    stats: dict[str, dict[str, Any]] = {}
    subreddit_counts: dict[str, Counter[str]] = defaultdict(Counter)
    group_counts: dict[str, Counter[str]] = defaultdict(Counter)
    submission_sets: dict[str, set[str]] = defaultdict(set)

    for comment in comments:
        author = comment.get("author_clean")
        if not author:
            continue
        if author not in stats:
            stats[author] = {
                "author": author,
                "comments": 0,
                "candidate_corrections": 0,
            }
        stats[author]["comments"] += 1
        if comment["candidate_correction"]:
            stats[author]["candidate_corrections"] += 1
        subreddit_counts[author][str(comment.get("subreddit"))] += 1
        group_counts[author][str(comment.get("community_group_proxy"))] += 1
        submission_sets[author].add(str(comment.get("submission_id") or ""))

    rows = []
    for author, row in stats.items():
        sub_counts = subreddit_counts[author]
        grp_counts = group_counts[author]
        row["subreddits_observed"] = len(sub_counts)
        row["community_groups_observed"] = len(grp_counts)
        row["subreddit_entropy"] = entropy(sub_counts)
        row["community_group_entropy"] = entropy(grp_counts)
        row["submissions_observed"] = len(submission_sets[author])
        row["candidate_correction_rate"] = safe_div(row["candidate_corrections"], row["comments"])
        row["cross_subreddit_observed"] = row["subreddits_observed"] > 1
        row["cross_group_observed"] = row["community_groups_observed"] > 1
        rows.append(row)

    return sorted(rows, key=lambda item: (item["subreddits_observed"], item["comments"]), reverse=True)


def aggregate_by_key(rows: list[dict[str, Any]], key: str) -> list[dict[str, Any]]:
    grouped: dict[str, dict[str, Any]] = {}
    for row in rows:
        value = str(row.get(key) or "unknown")
        if value not in grouped:
            grouped[value] = {
                key: value,
                "threads": 0,
                "comments": 0,
                "unique_authors": 0,
                "candidate_corrections": 0,
                "candidate_correctors": 0,
                "exposed_but_not_candidate_correctors": 0,
                "threads_with_candidate_correction": 0,
            }
        item = grouped[value]
        item["threads"] += 1
        item["comments"] += int(row.get("comments") or 0)
        item["unique_authors"] += int(row.get("unique_authors") or 0)
        item["candidate_corrections"] += int(row.get("candidate_corrections") or 0)
        item["candidate_correctors"] += int(row.get("candidate_correctors") or 0)
        item["exposed_but_not_candidate_correctors"] += int(row.get("exposed_but_not_candidate_correctors") or 0)
        if row.get("has_candidate_correction"):
            item["threads_with_candidate_correction"] += 1

    out = []
    for item in grouped.values():
        item["candidate_comment_rate"] = safe_div(item["candidate_corrections"], item["comments"])
        item["candidate_author_rate"] = safe_div(item["candidate_correctors"], item["unique_authors"])
        item["thread_candidate_presence_rate"] = safe_div(item["threads_with_candidate_correction"], item["threads"])
        out.append(item)
    return sorted(out, key=lambda item: item["candidate_comment_rate"], reverse=True)


def sample_annotation_rows(comments: list[dict[str, Any]], sample_per_group: int, seed: int) -> list[dict[str, Any]]:
    rng = random.Random(seed)
    buckets: dict[tuple[str, bool], list[dict[str, Any]]] = defaultdict(list)
    for comment in comments:
        body = str(comment.get("body") or "")
        if not body or body in {"[deleted]", "[removed]"}:
            continue
        buckets[(str(comment.get("community_group_proxy")), bool(comment.get("candidate_correction")))].append(comment)

    rows = []
    annotation_id = 1
    for (group, candidate), bucket in sorted(buckets.items()):
        selected = rng.sample(bucket, min(sample_per_group, len(bucket)))
        for comment in selected:
            body = collapse_whitespace(comment.get("body"))
            title = collapse_whitespace(comment.get("submission_title"))
            rows.append(
                {
                    "annotation_id": f"A{annotation_id:04d}",
                    "gold_label": "",
                    "is_public_correction": "",
                    "candidate_correction": int(candidate),
                    "community_group_proxy": group,
                    "subreddit": comment.get("subreddit"),
                    "comment_id": comment.get("comment_id"),
                    "submission_id": comment.get("submission_id"),
                    "parent_id": comment.get("parent_id"),
                    "level": comment.get("level"),
                    "submission_title": title,
                    "body": body,
                }
            )
            annotation_id += 1
    return rows


def collapse_whitespace(value: Any) -> str:
    return " ".join(str(value or "").split())


def safe_div(num: int | float, den: int | float) -> float:
    return float(num) / float(den) if den else 0.0


def write_codebook(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """# Annotation Codebook: Public Correction Pilot

## Unit

The annotation unit is one Reddit comment.

## Main Label

`is_public_correction`

- `1`: The comment publicly challenges, corrects, debunks, fact-checks, or provides evidence against a misinformation claim in the thread.
- `0`: The comment does not perform public correction, even if it discusses vaccines, COVID-19, institutions, or politics.
- `U`: Unclear from the comment alone.

## Coding Guidance

Mark `1` when the comment contains at least one of the following:

- direct rejection of a false or misleading claim;
- factual correction with evidence or source;
- link or reference to fact-checking, official data, or scientific evidence;
- explanation that a cited claim, image, statistic, or causal inference is wrong.

Mark `0` when the comment is only:

- agreement, insult, sarcasm, or general opinion;
- personal experience without correcting another claim;
- generic pro-vaccine or anti-vaccine stance without correcting a specific claim;
- request for information without correction.

Use `U` when the comment depends on missing context and the correction function cannot be determined.

## Important Boundary

The `candidate_correction` column is a keyword retrieval flag, not a ground-truth label. Annotators should ignore it when assigning `is_public_correction`.
""",
        encoding="utf-8",
    )


def write_run_report(path: Path, summary: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = f"""# Pilot Report: Reddit COVID Vaccine Correction Data

## Purpose

This exploratory run tests whether a real Reddit dataset can support the proposed correction-misallocation study. The run checks three empirical requirements: candidate public corrections must be observable, exposed-but-not-correcting users must be constructible at the thread level, and users must show enough cross-community variation to support structural heterogeneity measures.

## Data Scope

- Dataset: `{summary["dataset"]}`
- Comments: `{summary["comments"]:,}`
- Threads: `{summary["threads"]:,}`
- Subreddits: `{summary["subreddits"]:,}`
- Observed non-deleted users: `{summary["users"]:,}`

## Preliminary Signals

- Candidate correction comments: `{summary["candidate_correction_comments"]:,}`
- Threads with at least one candidate correction: `{summary["threads_with_candidate_correction"]:,}`
- Exposed-but-not-candidate-correcting users at the thread level: `{summary["exposed_but_not_candidate_correctors"]:,}`
- Users observed in more than one subreddit: `{summary["cross_subreddit_users"]:,}`
- Users observed in more than one community group: `{summary["cross_group_users"]:,}`

## Interpretation Boundary

The current `candidate_correction` flag is a retrieval aid rather than a validated public-correction label. The results support feasibility, not a substantive finding. The next step is manual annotation of the sampled comments and validation of a correction classifier.
"""
    path.write_text(text, encoding="utf-8")


def run(args: argparse.Namespace) -> None:
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    output_dir = args.output_dir or Path(f"outputs/pilot_covidvaccine_descriptive_{timestamp}")
    metrics_dir = output_dir / "metrics"
    tables_dir = output_dir / "tables"
    annotation_dir = output_dir / "annotation"
    output_dir.mkdir(parents=True, exist_ok=True)
    metrics_dir.mkdir(exist_ok=True)
    tables_dir.mkdir(exist_ok=True)
    annotation_dir.mkdir(exist_ok=True)

    comments = load_comments(args.comments)
    thread_profiles = build_thread_profiles(comments)
    user_profiles = build_user_profiles(comments)
    subreddit_profiles = aggregate_by_key(thread_profiles, "subreddit")
    group_profiles = aggregate_by_key(thread_profiles, "community_group_proxy")
    annotation_rows = sample_annotation_rows(comments, args.sample_per_group, args.seed)

    valid_users = [user for user in user_profiles if user["comments"] >= args.min_user_comments]
    summary = {
        "dataset": "christinegu27/reddit_covidvaccine_data",
        "run_status": "exploratory",
        "comments": len(comments),
        "threads": len(thread_profiles),
        "subreddits": len({comment.get("subreddit") for comment in comments}),
        "users": len(user_profiles),
        "users_min_comment_threshold": args.min_user_comments,
        "users_at_threshold": len(valid_users),
        "candidate_correction_comments": sum(1 for comment in comments if comment["candidate_correction"]),
        "threads_with_candidate_correction": sum(1 for row in thread_profiles if row["has_candidate_correction"]),
        "exposed_but_not_candidate_correctors": sum(
            int(row["exposed_but_not_candidate_correctors"]) for row in thread_profiles
        ),
        "cross_subreddit_users": sum(1 for user in valid_users if user["cross_subreddit_observed"]),
        "cross_group_users": sum(1 for user in valid_users if user["cross_group_observed"]),
        "annotation_rows": len(annotation_rows),
        "sample_per_group": args.sample_per_group,
        "seed": args.seed,
        "output_dir": str(output_dir),
    }

    write_json(metrics_dir / "run_summary.json", summary)
    write_csv(
        tables_dir / "subreddit_profiles.csv",
        subreddit_profiles,
        [
            "subreddit",
            "threads",
            "comments",
            "unique_authors",
            "candidate_corrections",
            "candidate_correctors",
            "exposed_but_not_candidate_correctors",
            "threads_with_candidate_correction",
            "candidate_comment_rate",
            "candidate_author_rate",
            "thread_candidate_presence_rate",
        ],
    )
    write_csv(
        tables_dir / "community_group_profiles.csv",
        group_profiles,
        [
            "community_group_proxy",
            "threads",
            "comments",
            "unique_authors",
            "candidate_corrections",
            "candidate_correctors",
            "exposed_but_not_candidate_correctors",
            "threads_with_candidate_correction",
            "candidate_comment_rate",
            "candidate_author_rate",
            "thread_candidate_presence_rate",
        ],
    )
    write_csv(
        tables_dir / "thread_profiles_top.csv",
        thread_profiles[:200],
        [
            "submission_id",
            "subreddit",
            "community_group_proxy",
            "comments",
            "unique_authors",
            "candidate_corrections",
            "candidate_correctors",
            "exposed_but_not_candidate_correctors",
            "candidate_comment_rate",
            "candidate_author_rate",
            "submission_title",
        ],
    )
    write_csv(
        tables_dir / "user_profiles_top.csv",
        user_profiles[:500],
        [
            "author",
            "comments",
            "candidate_corrections",
            "candidate_correction_rate",
            "submissions_observed",
            "subreddits_observed",
            "community_groups_observed",
            "subreddit_entropy",
            "community_group_entropy",
            "cross_subreddit_observed",
            "cross_group_observed",
        ],
    )
    write_csv(
        annotation_dir / "annotation_sample.csv",
        annotation_rows,
        [
            "annotation_id",
            "gold_label",
            "is_public_correction",
            "candidate_correction",
            "community_group_proxy",
            "subreddit",
            "comment_id",
            "submission_id",
            "parent_id",
            "level",
            "submission_title",
            "body",
        ],
    )
    write_codebook(annotation_dir / "annotation_codebook.md")
    write_run_report(output_dir / "pilot_report.md", summary)

    print(f"Wrote pilot outputs to {output_dir}")
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Analyze the Reddit COVID vaccine pilot dataset.")
    parser.add_argument("--comments", type=Path, default=Path("data/interim/covidvaccine_comments.jsonl"))
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--sample-per-group", type=int, default=60)
    parser.add_argument("--min-user-comments", type=int, default=2)
    parser.add_argument("--seed", type=int, default=20260624)
    return parser


def main() -> None:
    parser = build_parser()
    run(parser.parse_args())


if __name__ == "__main__":
    main()
