#!/usr/bin/env python3
"""Annotate Reddit comments with a local chat LLM.

This script is designed for WSA-side Qwen annotation. It treats the model output
as LLM-assisted labels, not human ground truth. The expected input is the
`annotation_sample.csv` generated by `analyze_covidvaccine_pilot.py`.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


SYSTEM_PROMPT = """You are annotating Reddit comments for a misinformation-correction study.

Do not think step by step. Do not include hidden reasoning. Return only the final JSON object.

Task: decide whether the target comment performs public correction.

Label definitions:
- 1: The comment publicly challenges, corrects, debunks, fact-checks, or provides evidence against a misinformation claim in the thread.
- 0: The comment does not perform public correction.
- U: The correction function is unclear from the comment and submission title alone.

Mark 1 only when the comment contains at least one of the following:
- direct rejection of a false or misleading claim;
- factual correction with evidence or a source;
- reference to fact-checking, official data, scientific evidence, or a credible corrective source;
- explanation that a cited claim, image, statistic, or causal inference is wrong.

Mark 0 when the comment is only:
- agreement, insult, sarcasm, or general opinion;
- personal experience without correcting another claim;
- generic pro-vaccine or anti-vaccine stance without correcting a specific claim;
- request for information without correction.

Return only valid JSON with these fields:
{
  "is_public_correction": "1|0|U",
  "confidence": 0.0,
  "correction_target": "short description or empty string",
  "rationale": "one concise sentence"
}
"""


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False, sort_keys=True) + "\n")


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        return []
    rows = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def annotation_key(row: dict[str, Any]) -> str:
    return str(row.get("annotation_id") or row.get("comment_id") or "")


def build_user_prompt(row: dict[str, str]) -> str:
    parent_body = str(row.get("parent_body", "") or "").strip()
    parent_section = ""
    if parent_body:
        parent_section = f"""
Parent comment being replied to:
{parent_body}
"""
    return f"""Submission title:
{row.get("submission_title", "")}

Subreddit:
{row.get("subreddit", "")}
{parent_section}
Comment:
{row.get("body", "")}

Does the comment perform public correction?"""


def extract_json(text: str) -> dict[str, Any]:
    text = text.strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if match:
        try:
            return json.loads(match.group(0))
        except json.JSONDecodeError:
            pass
    return {
        "is_public_correction": "U",
        "confidence": 0.0,
        "correction_target": "",
        "rationale": "Model output could not be parsed as JSON.",
    }


def normalize_label(value: Any) -> str:
    value = str(value).strip().upper()
    if value in {"1", "TRUE", "YES", "Y"}:
        return "1"
    if value in {"0", "FALSE", "NO", "N"}:
        return "0"
    return "U"


def normalize_confidence(value: Any) -> float:
    try:
        confidence = float(value)
    except (TypeError, ValueError):
        return 0.0
    return max(0.0, min(1.0, confidence))


def normalize_device_map(device_map: str) -> Any:
    if device_map in {"auto", "balanced", "balanced_low_0", "sequential"}:
        return device_map
    if device_map.startswith("cuda") or device_map == "cpu":
        return {"": device_map}
    return device_map


def load_model(
    model_path: str,
    dtype: str,
    device_map: str,
    trust_remote_code: bool,
    attn_implementation: str,
) -> tuple[Any, Any]:
    import torch
    from transformers import AutoModelForCausalLM, AutoTokenizer

    dtype_map = {
        "auto": "auto",
        "float16": torch.float16,
        "bfloat16": torch.bfloat16,
        "float32": torch.float32,
    }
    tokenizer = AutoTokenizer.from_pretrained(model_path, trust_remote_code=trust_remote_code)
    model_kwargs = {
        "device_map": normalize_device_map(device_map),
        "trust_remote_code": trust_remote_code,
    }
    if attn_implementation != "auto":
        model_kwargs["attn_implementation"] = attn_implementation
    try:
        model = AutoModelForCausalLM.from_pretrained(model_path, dtype=dtype_map[dtype], **model_kwargs)
    except TypeError:
        model = AutoModelForCausalLM.from_pretrained(model_path, torch_dtype=dtype_map[dtype], **model_kwargs)
    model.eval()
    return tokenizer, model


def generate_one(
    tokenizer: Any,
    model: Any,
    system_prompt: str,
    user_prompt: str,
    max_new_tokens: int,
    temperature: float,
) -> str:
    import torch

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    if hasattr(tokenizer, "apply_chat_template") and tokenizer.chat_template:
        try:
            prompt = tokenizer.apply_chat_template(
                messages,
                tokenize=False,
                add_generation_prompt=True,
                enable_thinking=False,
            )
        except TypeError:
            prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    else:
        prompt = f"System:\n{system_prompt}\n\nUser:\n{user_prompt}\n\nAssistant:\n"

    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    generation_kwargs = {
        "max_new_tokens": max_new_tokens,
        "do_sample": temperature > 0,
        "temperature": temperature if temperature > 0 else None,
        "pad_token_id": tokenizer.eos_token_id,
    }
    generation_kwargs = {k: v for k, v in generation_kwargs.items() if v is not None}

    with torch.inference_mode():
        output = model.generate(**inputs, **generation_kwargs)
    new_tokens = output[0][inputs["input_ids"].shape[-1] :]
    return tokenizer.decode(new_tokens, skip_special_tokens=True).strip()


def run(args: argparse.Namespace) -> None:
    start = time.time()
    input_rows = read_csv(args.input)
    if args.limit:
        input_rows = input_rows[: args.limit]

    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    metrics_dir = output_dir / "metrics"
    metrics_dir.mkdir(exist_ok=True)

    output_csv = output_dir / "llm_annotations.csv"
    output_raw = output_dir / "llm_raw_outputs.jsonl"

    rows: list[dict[str, Any]] = []
    raw_rows: list[dict[str, Any]] = []
    completed_keys: set[str] = set()
    if args.resume and output_csv.exists():
        rows = read_csv(output_csv)
        raw_rows = read_jsonl(output_raw)
        completed_keys = {annotation_key(row) for row in rows if annotation_key(row)}
        input_rows = [row for row in input_rows if annotation_key(row) not in completed_keys]

    tokenizer, model = load_model(
        args.model,
        args.dtype,
        args.device_map,
        args.trust_remote_code,
        args.attn_implementation,
    )

    csv_fields = list(read_csv(args.input)[0].keys()) + [
        "llm_label",
        "llm_confidence",
        "llm_correction_target",
        "llm_rationale",
    ]

    for index, row in enumerate(input_rows, 1):
        prompt = build_user_prompt(row)
        raw_output = generate_one(
            tokenizer=tokenizer,
            model=model,
            system_prompt=SYSTEM_PROMPT,
            user_prompt=prompt,
            max_new_tokens=args.max_new_tokens,
            temperature=args.temperature,
        )
        parsed = extract_json(raw_output)
        label = normalize_label(parsed.get("is_public_correction"))
        confidence = normalize_confidence(parsed.get("confidence"))

        out_row = dict(row)
        out_row.update(
            {
                "llm_label": label,
                "llm_confidence": confidence,
                "llm_correction_target": str(parsed.get("correction_target", "")),
                "llm_rationale": str(parsed.get("rationale", "")),
            }
        )
        rows.append(out_row)
        raw_rows.append(
            {
                "annotation_id": row.get("annotation_id"),
                "comment_id": row.get("comment_id"),
                "raw_output": raw_output,
                "parsed_output": parsed,
            }
        )
        if index % args.log_every == 0 or index == len(input_rows):
            print(f"Annotated {index}/{len(input_rows)}")
        if args.save_every and (index % args.save_every == 0):
            write_csv(output_csv, rows, csv_fields)
            write_jsonl(output_raw, raw_rows)

    write_csv(output_csv, rows, csv_fields)
    write_jsonl(output_raw, raw_rows)

    label_counts = {}
    for row in rows:
        label_counts[row["llm_label"]] = label_counts.get(row["llm_label"], 0) + 1

    summary = {
        "run_status": "exploratory_llm_assisted_annotation",
        "input": str(args.input),
        "output_dir": str(output_dir),
        "model": args.model,
        "rows": len(rows),
        "new_rows_this_run": len(input_rows),
        "resume": args.resume,
        "label_counts": label_counts,
        "temperature": args.temperature,
        "max_new_tokens": args.max_new_tokens,
        "dtype": args.dtype,
        "device_map": args.device_map,
        "trust_remote_code": args.trust_remote_code,
        "attn_implementation": args.attn_implementation,
        "started_utc": datetime.fromtimestamp(start, timezone.utc).isoformat(),
        "finished_utc": datetime.now(timezone.utc).isoformat(),
        "elapsed_seconds": time.time() - start,
    }
    (metrics_dir / "run_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True),
        encoding="utf-8",
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run local Qwen annotation for public correction labels.")
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--model", required=True, help="Local Hugging Face model path or model id.")
    parser.add_argument("--dtype", choices=["auto", "float16", "bfloat16", "float32"], default="bfloat16")
    parser.add_argument("--device-map", default="auto")
    parser.add_argument("--trust-remote-code", action="store_true")
    parser.add_argument("--attn-implementation", choices=["auto", "sdpa", "flash_attention_2", "eager"], default="auto")
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--max-new-tokens", type=int, default=220)
    parser.add_argument("--limit", type=int, default=0)
    parser.add_argument("--log-every", type=int, default=20)
    parser.add_argument("--save-every", type=int, default=50)
    parser.add_argument("--resume", action="store_true")
    return parser


def main() -> None:
    parser = build_parser()
    run(parser.parse_args())


if __name__ == "__main__":
    main()
